stages:
  - docker-build-llvm
  - docker-build-mlir-sdk
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

docker-build-llvm:
  stage: docker-build-llvm
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${DOCKER_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.llvm-project"
      --destination "onesai1/onnx-mlir-llvm:${CI_COMMIT_REF_NAME}"
      --destination "onesai1/onnx-mlir-llvm:latest"
      --build-arg "NPROC=40"
      --build-arg "LLVM_PROJECT_SHA1=b2cdf3cc4c08729d0ff582d55e40793a20bbcdcc"
  tags:
    - etri-compute
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      changes:
        - docker/Dockerfile.llvm-project

docker-build-llvm-no-push:
  stage: docker-build-llvm
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.llvm-project"
      --build-arg "NPROC=40"
      --build-arg "LLVM_PROJECT_SHA1=b2cdf3cc4c08729d0ff582d55e40793a20bbcdcc"
      --no-push
  tags:
    - etri-compute
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "false"
      changes:
        - docker/Dockerfile.llvm-project

docker-build-mlir-sdk:
  stage: docker-build-mlir-sdk
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${DOCKER_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.onnx-mlir-part-sdk"
      --destination "onesai1/onnx-mlir-part-sdk:${CI_COMMIT_REF_NAME}"
      --destination "onesai1/onnx-mlir-part-sdk:latest"
      --build-arg "BASE_IMAGE=onesai1/onnx-mlir-llvm:latest"
      --build-arg "NPROC=40"
  tags:
    - etri-compute
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      changes:
        - docker/Dockerfile.onnx-mlir-part-sdk

docker-build-mlir-sdk-no-push:
  stage: docker-build-mlir-sdk
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.onnx-mlir-part-sdk"
      --build-arg "BASE_IMAGE=onesai1/onnx-mlir-llvm:latest"
      --build-arg "NPROC=40"
      --destination "onesai1/onnx-mlir-part-sdk:latest"
  tags:
    - etri-compute
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "false"
      changes:
        - docker/Dockerfile.onnx-mlir-part-sdk
        - .gitlab-ci.yml

build:
  stage: build
  image: onesai1/onnx-mlir-part-sdk:latest
  variables:
    AWS_ENDPOINT_URL: ${MINIO_SERVER_URL}
    AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    AWS_DEFAULT_REGION: us-east-1
    NPROC: 40
    ACCEL: NNPA
    WORK_DIR: /workdir
    LLVM_PROJECT_ROOT: ${WORK_DIR}/llvm-project
    ONNX_MLIR_ROOT: ${WORK_DIR}/onnx-mlir
    CC: clang
    CXX: clang++
  before_script:
  #   - aws configure set aws_access_key_id ${MINIO_ACCESS_KEY}
  #   - aws configure set aws_secret_access_key ${MINIO_SECRET_KEY}
  #   - aws configure set default.region us-east-1
    - aws configure set default.s3.signature_version s3v4
    - cd ${ONNX_MLIR_ROOT} && rm -rf build && mkdir -p build && cd build
  script:
    - MLIR_DIR=${LLVM_PROJECT_ROOT}/build/lib/cmake/mlir LIT_OPTS=-v cmake -G Ninja \
             -DCMAKE_CXX_COMPILER=/usr/bin/c++ \
             -DCMAKE_CXX_FLAGS="-w" \
             -DMLIR_DIR=${MLIR_DIR} \
             .. \
    - cmake --build .
    - cmake --build . --target check-onnx-lit
