/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===------------------------ NNPACompilerOptions.hpp ---------------------===//
//
// Copyright 2022-2024 The IBM Research Authors.
//
// =============================================================================
//
//
//===----------------------------------------------------------------------===//

#ifndef ONNX_MLIR_ARX_COMPILER_OPTIONS_H
#define ONNX_MLIR_ARX_COMPILER_OPTIONS_H

#define INSTRUMENTSTAGE_ENUM_ARX                                               \
    , ARX \
    
#define INSTRUMENTSTAGE_CL_ENUM_ARX                                           \
  clEnumVal(Onnx, "Profile for onnx ops. For NNPA, profile onnx ops before "   \
                  "lowering to zhigh."),                                       \
      clEnumVal(ARX, "NNPA profiling for onnx and zhigh ops.")

#define PROFILEIR_CL_ENUM_ARX                                                 \
  , clEnumVal(ARX, "Profile operations in ARXIR generated by "             \
                     "--EmitARXIR.")

#define OPTREPORT_ENUM_ARX , ARXUnsupportedOps

#define OPTREPORT_CL_ENUM_ARX                                                 \
  , clEnumVal(ARXUnsupportedOps,                                              \
        "Provide report on why ONNX ops did not run on ARX.")

#endif
