/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===------------------------ NNPACompilerOptions.hpp ---------------------===//
//
// Copyright 2022-2024 The IBM Research Authors.
//
// =============================================================================
//
//
//===----------------------------------------------------------------------===//

#ifndef ONNX_MLIR_ARX_COMPILER_OPTIONS_H
#define ONNX_MLIR_ARX_COMPILER_OPTIONS_H

#include "llvm/Support/CommandLine.h"

#define INSTRUMENTSTAGE_ENUM_ARX                                               \
    , HARX, LARX \
    
#define INSTRUMENTSTAGE_CL_ENUM_ARX                                           \
  clEnumVal(Onnx, "Profile for onnx ops. For HARX, profile onnx ops before "   \
                  "lowering to zhigh."),                                     \
      clEnumVal(HARX, "HARX profiling for onnx and zhigh ops."), \
      clEnumVal(LARX, "LARX profiling for onnx and zhigh ops.")

#define PROFILEIR_CL_ENUM_ARX                                                 \
  , clEnumVal(HARX, "Profile operations in HARXIR generated by "             \
                     "--EmitHARXIR.")        \
  , clEnumVal(LARX, "Profile operations in LARXIR generated by "             \
                     "--EmitLARXIR.")

#define OPTREPORT_ENUM_ARX , ARXUnsupportedOps

#define OPTREPORT_CL_ENUM_ARX                                                 \
  , clEnumVal(ARXUnsupportedOps,                                              \
        "Provide report on why ONNX ops did not run on ARX.")
namespace onnx_mlir {

typedef enum {
  EmitANONE,
  EmitHARXIR,
  EmitLARXIR,
} ARXEmissionTargetType;

// typedef enum {
//   QualifyingOps,    /* Any ops that qualify for NNPA will go on NNPA. */
//   FasterOps,        /* Only qualifying ops that are faster on NNPA */
//   FasterOpsWSU,     /* FasterOps with With Stick and Unstick (WSU) cost.*/
//   MuchFasterOpsWSU, /* FasterOpsWSU only if significantly faster. */
// } ARXPlacementHeuristic;

extern llvm::cl::OptionCategory OnnxMlirOptions;
extern llvm::cl::OptionCategory OnnxMlirCommonOptions;
extern llvm::cl::opt<bool> arxEnableCuteChaCha;
}

#endif
