---
- name: CPU
  backendName: x86
  deviceID: 0
  isDefaultDevice : true
  supportedOps: All
  emitType: Obj
- name: NPU1
  backendName: EVTA
  supportedOps: SoftMax
  deviceID: 1
  emitType: Lib
- name: NPU2
  backendName: EVTA
  supportedOps: Convolution
  deviceID: 2
  emitType: IR
...
