ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS onnx-mlir-test

ARG WORK_DIR=/workdir
WORKDIR ${WORK_DIR}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends python3-pybind11 libyaml-cpp-dev libpng-dev curl unzip

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip -qq awscliv2.zip && ./aws/install && rm awscliv2.zip
